### ISSUE TITLE
Rejected from Google due to OpenSSL version issue. 

### ISSUE THREAD

**Issue by inturbidus** [Kickflip/kickflip-android-sdk#57]
I believe this is from FFMPEGs use of OpenSSL.  Can it be upgraded to 1.0.1h, 1.0.0m, or 0.9.8za?

**Comment by chrisballinger** [comment]
Yes there should be no issue with upgrading the OpenSSL libraries

**Comment by inturbidus** [comment]
Here's what they said https://support.google.com/faqs/answer/6376725?hl=en

**Comment by inturbidus** [comment]
Can you help with this or point me in the right direction?

**Comment by OnlyInAmerica** [comment]
Thanks for the report! I'll see if I can fix this tomorrow, and add clearer
instructions for future upgrades.

**Comment by OnlyInAmerica** [comment]
I've updated FFmpeg to 2.8.7 (3.X will require changes to the JNI Bridge) and removed OpenSSL since that was only used for RTMP support which has been removed from this project. You can trial the changes in the [`ffmpeg287`](https://github.com/Kickflip/kickflip-android-sdk/tree/ffmpeg287) branch. Currently just the arm shared libraries are included. If you have success I'll merge #58 and release the update.

To make updating FFmpeg and the JNI bridge easier I've moved the bridge into this project directly, and added more complete instructions to [DEVELOPMENT.md](https://github.com/Kickflip/kickflip-android-sdk/blob/ffmpeg287/DEVELOPMENT.md). In short: 

**To update FFmpeg in the future**:
1. Build FFmpeg shared libraries ([instructions](https://github.com/OnlyInAmerica/FFmpeg-Android)) and copy the libav\* shared libraries to `./src/main/jni/ffmpeg/ARCH` and their headers to `./src/main/jni/include`
2. Update the JNI bridge at `./src/main/jni/FFmpegWrapper.c` if necessary (FFmpeg 3.x)
3. Invoke `ndk-build` from `./src/main/jni`.

**Comment by inturbidus** [comment]
Great! Appreciated! I'll test it out and reply.

**Comment by inturbidus** [comment]
Resolved.  Thank you.
